name: Deploy to AWS EC2

on:
  push:
    branches:
    - deploy
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.ACCESO_DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_NAME }}/front_eval2:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_NAME }}/front_eval2:latest

      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".env"
          target: "/home/${{ secrets.EC2_USER }}/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_NAME }}/front_eval2:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 80:5000 --env-file .env --name frontend ${{ secrets.DOCKER_NAME }}/front_eval2:latest