name: Deploy to AWS EC2

on:
  push:
    branches:
    - deploy
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.ACCESO_DOCKERHUB_PASS }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_NAME }}/front_eval2:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_NAME }}/front_eval2:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_NAME }}/front_eval2:latest
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 8080:5000 \
              -e PORT=5000 \
              -e DEBUG=False \
              -e BACKEND_URL=http://10.0.133.201:3000 \
              -e SECRET_KEY=clave_secreta_muy_segura_aqui \
              --name frontend ${{ secrets.DOCKER_NAME }}/front_eval2:latest